# Upstreams
upstream flow_backend_upstream {
    least_conn;
    server 127.0.0.1:3022;
    keepalive 64;
}

upstream flow_frontend_upstream {
    least_conn;
    server 127.0.0.1:3021;
    keepalive 32;
}

upstream flow_evolution_upstream {
    server 127.0.0.1:8081;
    keepalive 16;
}

# BACKEND
server {
    server_name api.flow.nkwflow.com;

    large_client_header_buffers 4 32k;

    location / {
        proxy_pass http://flow_backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffer_size   128k;
        proxy_buffers   4 256k;
        proxy_busy_buffers_size   256k;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/api.flow.nkwflow.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.flow.nkwflow.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# EVOLUTION API
server {
    server_name evolution.nkwflow.com;

    location / {
        proxy_pass http://flow_evolution_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/evolution.nkwflow.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/evolution.nkwflow.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# FRONTEND NEXT.JS
server {
    server_name flow.nkwflow.com;

    location / {
        proxy_pass http://flow_frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    listen 443 ssl http2;
    ssl_certificate /etc/letsencrypt/live/flow.nkwflow.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/flow.nkwflow.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

# REDIRECIONAMENTOS HTTPS MANDATÓRIOS
server {
    if ($host = flow.nkwflow.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name flow.nkwflow.com;
    return 404; # managed by Certbot
}

server {
    if ($host = api.flow.nkwflow.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name api.flow.nkwflow.com;
    return 404; # managed by Certbot
}

server {
    if ($host = evolution.nkwflow.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name evolution.nkwflow.com;
    return 404; # managed by Certbot
}
